### ISSUE TITLE
Liberação do Projeto!

### ISSUE THREAD

**Issue by fredwilliamtjr** [Samuel-Oliveira/Java_MDFe#2]
Grande Samuel, tem mais ou menos ideia de quando esse projeto estará liberado? precisa de ajuda para terminal algo para liberar para a galera?

**Comment by Samuel-Oliveira** [comment]
Blz? A priore essa API foi financiada por uma empresa, e eu fiz mais da metade do projeto. Mas a Empresa acabou não cumprindo com os honorários. Então eu acabei pausando até outra estar financiando ou eu arrumar tempo, então por enquanto ela não é prioridade!

**Comment by fredwilliamtjr** [comment]
Entendi,  me diga uma coisa, em janeiro eu vou precisar adicionar MDFe no meu projeto, eu gostaria de ajudar a terminar o projeto, seria uma opção?

**Comment by Samuel-Oliveira** [comment]
Infelizmente no Estagio que o projeto está seria mais fácil você construir do zero do que parar e te encaminhar para o que você deveria fazer e como!
